### ISSUE TITLE
Exposing more methods for finding policies

### ISSUE THREAD

**Issue by ugodiggi** [ory/ladon#119]
This is a followup to the conversation on https://community.ory.sh/t/exposing-more-methods-for-finding-policies/555/

It would be helpful for me to have more nuanced methods for finding policies, in particular I’d like to expose in the Manager interface an explicit method for FindPoliciesForResource.
I can provide a pull request for this for ladon, that is efficient for MySQL/Postgresql.

**Comment by arekkas** [comment]
The reason for this not being implemented right now is that the library actually doesn't need that. I'm thinking if it would make sense to have it as a separate library that extends this manager so it's more like an add-in as opposed to a first-class citizen. What do you think?

**Comment by ugodiggi** [comment]
I pushed a pull request for reference (https://github.com/ory/ladon/pull/120) for what I have in mind.

The core question for me is how to fit this in the manager interface, so that I can use the memory manager for testing and the Postgres manager in production. Can you give me more details on what you imagine as a separate library?

**Comment by ugodiggi** [comment]
Thank you for the fast review!
