### ISSUE TITLE
MemoryManager.GetAll() return random policies

### ISSUE THREAD

**Issue by datastream** [ory/ladon#126]
If I call memory.GetAll(10,0), every time it return different data.
https://github.com/ory/ladon/blob/d66f876581b5f713b5452e639d3113f23223154a/manager/memory/manager_memory.go#L54

so I think this function should be sort first.

```
        var keys []string
        m. RLock()  
        start, end := pagination.Index(int(limit), int(offset), len(m.Policies))
	for key, p := range m.Policies {
                keys = append(keys, key)
	}
        sort.Ints(keys)
        var rst []Policies
         for _, key := range keys[start:end] {
                  rst = append(rst, m.Policies[key])
        }
        m. RUnlock()
	return rst, nil
```

**Comment by aeneasr** [comment]
It would probably be better to change the internal storage of the policies from a map to a slice, which would save us some time sorting and appending here. As a side note, `var keys []string` is not initialized so `append` will allocate by power of 2 which takes a lot of time in pressure environments. You can save a lot of unnecessary allocation with `keys := make([]string, len(m.Policies))`

Feel free to PR according to my feedback!
