### ISSUE TITLE
Incorrect examples?

### ISSUE THREAD

**Issue by cemremengu** [ory/ladon#130]
As the examples suggest I am trying:

```go
	accessRequest := &ladon.Request{
		Subject:  "max",
		Resource: "myrn:some.domain.com:resource:123",
		Action:   "update",
		Context: &ladon.Context{
			"some-arbitrary-key": "the-value-should-be-this",
		},
	}
```

However the compile complains for `&ladon.Context` saying that it should be `ladon.Context`. Am I doing something wrong? I can send a PR to fix the examples if that is the case.

**Comment by aeneasr** [comment]
Yeah it should be `ladon.Context`, feel free to PR :)
