### ISSUE TITLE
Ladon Manager datastore future issues?

### ISSUE THREAD

**Issue by jsimnz** [ory/ladon#134]
-- More of a question

Was there a fundamental problem or limitation with the Ladon framework that forced the Keto server to replace it with the OPA Rego system? Or, was it just a question of easier achieving the desired goals with OPA?

I want to use the Ladon framework in a somewhat specialized way and was wondering if I am wasting my time because there's some major issue with it. The Keto issue that raised the first problem with Ladon cited an issue with fast writes to the policy creations caused conflicts, can this be (by myself obviously) resolved by implementing an appropriate ladon.Manager?s

**Comment by aeneasr** [comment]
> The Keto issue that raised the first problem with Ladon cited an issue with fast writes to the policy creations caused conflicts, can this be (by myself obviously) resolved by implementing an appropriate ladon.Manager?

Absolutely! Most policies will live in memory or on disk anyways!

> Was there a fundamental problem or limitation with the Ladon framework that forced the Keto server

No, we just wanted to have more concepts in Keto than just Ladon policies! OPA was a pretty good fit to support that.

**Comment by jsimnz** [comment]
Thanks for the quick response Hackerman! Ill go ahead and close this.
