### ISSUE TITLE
I need understand what's plan of this project

### ISSUE THREAD

**Issue by kubitre** [ory/ladon#153]
Hello! Please, tell me about this project. I would like to use this project in my pet project for accessing control. Maybe u have Manager policy like mongodb? Or anything else?

**Comment by aeneasr** [comment]
So your question is if it has a storage backend?

**Comment by kubitre** [comment]
Yes, I also wanted to know if this project will develop?

**Comment by aeneasr** [comment]
The project is considered feature complete - if you find a bug then we'll definitely fix it. If you request a new feature, it will most likely not be added from our end. We'll of course review PRs but please discuss them first.

Regarding storage adapters, you will need to implement your own as there are none available here!
