### ISSUE TITLE
Add MongoDB support

### ISSUE THREAD

**Issue by DenisNeustroev** [ory/ladon#25]

**Comment by arekkas** [comment]
Feel free to give it a go. References are:

* [manager_postgres.go](manager_postgres.go)
* [manager_memory.go](manager_postgres.go)
* [manager.go](manager_postgres.go)

**Comment by arekkas** [comment]
This will not make it in the official repository, closing.

**Comment by finnZhang0710** [comment]
Seems that links you've given above are broken

**Comment by aeneasr** [comment]
You can find them in the commit history. Ladon no longer provides storage implementations!

**Comment by finnZhang0710** [comment]
I have found them, thanks! but out of curiosity, i just want to know why they are not supported anymore.
> This will not make it in the official repository, closing.

**Comment by aeneasr** [comment]
Because it's too much work for us

**Comment by finnZhang0710** [comment]
thanks for your time again!

**Comment by aeneasr** [comment]
no problem!
